FROM antimodes201/steamcmd-base:1.0
MAINTAINER antimodes201

# Set some Variables
ARG GAME_PORT=27015
ARG QUERY_PORT=7777
ARG STEAM_PORT=8766
ARG WEB_SERVER=8889

ENV BRANCH "public"
ENV INSTANCE_NAME "default"
ENV GAME_PORT $GAME_PORT
ENV QUERY_PORT $QUERY_PORT
ENV STEAM_PORT $STEAM_PORT
ENV WEB_SERVER $WEB_SERVER


ADD start.sh /scripts/start.sh
ADD Game.ini /scripts/Game.ini
ADD Engine.ini /scripts/Engine.ini

# Expose some port
EXPOSE $GAME_PORT/udp
EXPOSE $QUERY_PORT/udp
EXPOSE $STEAM_PORT/tcp
EXPOSE $STEAM_PORT/udp
EXPOSE $WEB_SERVER/tcp
EXPOSE $WEB_SERVER/udp

CMD ["/scripts/start.sh"]